# Generated by Django 4.2.7 on 2023-11-06 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatgpt', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userquestion',
            name='conversation_history',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
